#!/usr/bin/php
<?php
require '../../autoload.php';

$x = new Zf2mb\Filesystem();

exit;

$modCC = $argv[1];

echo PHP_EOL . 'Building module ' . $modCC . '...'. PHP_EOL;

$filter  = new Zend\Filter\Word\CamelCaseToDash();

$modDS = strtolower($filter->filter($modCC));

$dirs = array(
	"$modCC/config",
	"$modCC/src/$modCC/Controller",
	"$modCC/src/$modCC/Form",
	"$modCC/src/$modCC/Model",
	"$modCC/view/$modDS/$modDS"
);

$root = realpath(__DIR__ . '/../../../module/');

echo 'Creating module in ' . $root . PHP_EOL;

foreach($dirs as $dir) {
	$fullDir = str_replace('/', DIRECTORY_SEPARATOR, $root . '/' . $dir);
	echo 'Creating ' . $fullDir . '...' . PHP_EOL;
	mkdir($fullDir, 0777, true);
}


echo PHP_EOL;